#!/bin/bash

mkdir -p ~/typespark-apps && cd ~/typespark-apps

echo "
 _______                 _____                  _    
|__   __|               / ____|                | |   
   | |_   _ _ __   ___ | (___  _ __   __ _ _ __| | __
   | | | | | '_ \ / _ \ \___ \| '_ \ / _\` | '__| |/ /
   | | |_| | |_) |  __/ ____) | |_) | (_| | |  |   < 
   |_|\__, | .__/ \___||_____/| .__/ \__,_|_|  |_|\_\\
       __/ | |                | |                    
      |___/|_|                |_|                    
"
echo "This script will create a new folder in ~/typespark-apps."
echo "That folder will contain a Vite app."
echo "It only works on Mac."

echo "WARNING: the test suite part of this script is probably broken right now."

read -p "Give the new app a name: " APP_NAME_INPUT


APP_NAME=$(echo "$APP_NAME_INPUT" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')

if [ "$APP_NAME" != "$APP_NAME_INPUT" ]; then
    echo "Name sanitized to: $APP_NAME"
fi

# Check if directory exists, if so, ask user if they want to overwrite
if [ -d "$APP_NAME" ]; then
    read -p "Directory $APP_NAME already exists. Do you want to overwrite it? (y/N): " OVERWRITE
    if [[ $OVERWRITE =~ ^[Yy]$ ]]; then
        rm -rf "$APP_NAME"
    else
        echo "Exiting. Please choose a different app name."
        exit 1
    fi
fi


if [ -z "$APP_NAME" ]; then
    echo "App name cannot be empty."
    exit 1
fi

# Function to check if response is affirmative or empty
# (this means all responses are Yes by default)
is_affirmative() {
    [[ "$1" =~ ^[Yy]$ ]] || [[ -z "$1" ]]
}

# Get user responses, and set booleans based on responses

read -p "Do you want to use Tailwind for styling? (Y/n): " ADD_TAILWIND_RESPONSE
ADD_TAILWIND=$(is_affirmative "$ADD_TAILWIND_RESPONSE" && echo true || echo false)


# Only offer database if user has said yes to a server
read -p "Do you want to add an Express server? (Y/n): " ADD_EXPRESS_RESPONSE
ADD_EXPRESS=$(is_affirmative "$ADD_EXPRESS_RESPONSE" && echo true || echo false)

if $ADD_EXPRESS; then
  read -p "Do you need a PostgreSQL database? (Y/n): " ADD_POSTGRES_RESPONSE
  ADD_POSTGRES=$(is_affirmative "$ADD_POSTGRES_RESPONSE" && echo true || echo false)
else
  ADD_POSTGRES=false
fi

# read -p "Do you to add Vitest for test coverage? (Y/n): " ADD_VITEST_RESPONSE
# ADD_VITEST=$(is_affirmative "$ADD_VITEST_RESPONSE" && echo true || echo false)
# temporary override
ADD_VITEST=false

# Define the path to the boilerplate files
BOILERPLATE_PATH=~/bin/boilerplates



echo "Building app with:
ADD_TAILWIND = $ADD_TAILWIND
ADD_EXPRESS = $ADD_EXPRESS
ADD_POSTGRES = $ADD_POSTGRES
ADD_VITEST = $ADD_VITEST
"

# Create the app folder and jump into it
mkdir $APP_NAME
cd $APP_NAME

# Create the frontend app
# If there is going to be a server as well, we want frontend in its own /frontend folder
# Otherwise we want it at the top level of the project
if $ADD_EXPRESS; then
  mkdir frontend
  cd frontend
fi

npm create vite@latest . -- --template react-swc-ts
npm install
npm init -y

if $ADD_TAILWIND; then
  # These track steps here https://tailwindcss.com/docs/guides/vite as of 2024-07-24
  npm install -D tailwindcss postcss autoprefixer
  npx tailwindcss init -p
  cp $BOILERPLATE_PATH/boilerplate.tailwind.config.js ./tailwind.config.js

# The sed command (to prepend text to a file) is finecky. This only works on Mac.
  sed -i '' '1i\
@tailwind base;\
@tailwind components;\
@tailwind utilities;\
' src/index.css

  echo "Tailwind CSS setup completed."
else
  echo "Tailwind CSS setup skipped."
fi


if $ADD_EXPRESS; then
  cd ..
fi

# PWD at end of a loop like this should always be project parent
# (e.g. APPS-FROM-SCRIPTS/app-name)


# Give the project a good gitignore and blank readme at top level
cp $BOILERPLATE_PATH/boilerplate.dotgitignore ./.gitignore
cp $BOILERPLATE_PATH/boilerplate.README.md ./README.md

# Clear away any pm2 processes that are already in place and might compete for a PORT slot
pm2 delete all



# Add an express server if requested
if $ADD_EXPRESS; then
  mkdir server
  cd server
    npm init -y
    npm install express cors
    npm i --save-dev @types/express @types/cors
    echo "Express server setup completed in the 'server' directory."
    cp $BOILERPLATE_PATH/boilerplate.server.ts ./server.ts
    echo "Boilerplate server file copied to '$APP_NAME/server/server.ts'."
    pm2 start 'bun --watch server.ts' --name devserver
  cd ..
  cp $BOILERPLATE_PATH/boilerplate.App.tsx frontend/src/App.tsx
  echo "Boilerplate client file updated with server routes in '$APP_NAME/frontend/src/App.tsx'."
else
  echo "Express server setup skipped."
fi




# Add a database if requested
if $ADD_POSTGRES; then
  cd server
    # Add docker compose template
    docker compose down
    cp $BOILERPLATE_PATH/boilerplate.docker-compose.yml ./docker-compose.yml
    echo "Boilerplate Docker yml files added."

    # Add Prisma and schema boilerplates
    npm install prisma --save-dev
    npx prisma init
    cp $BOILERPLATE_PATH/boilerplate.dotenv ./.env
    cp $BOILERPLATE_PATH/boilerplate.dotenv.test ./.env.test
    cp $BOILERPLATE_PATH/boilerplate.schema.prisma ./prisma/schema.prisma

    # Migrate schema and fire up in Docker. Keep this verbose it has caused hiccups in the past. 
    echo "============ running prisma migrate dev ============"
    npx prisma migrate dev --name initial-setup --force
    echo "============ running docker compose up in detached mode ============"
    docker compose up -d
    pm2 start 'npx prisma studio' --name prismastudio
  cd ..

else
  echo "Postgres setup skipped."
fi




# Add a test suite if requested
# PROBABLY BROKEN RIGHT NOW
if $ADD_VITEST; then
  npm install -D vitest

  if $ADD_POSTGRES; then
  npm install dotenv
  cp $BOILERPLATE_PATH/boilerplate.docker-compose.test.yml ./docker-compose.test.yml
  cp $BOILERPLATE_PATH/boilerplate.dotenv.test ./.env.test
  npm pkg set scripts.test:env="npx dotenv -e .env.test vitest"
  npm pkg set scripts.test:server:up="pm2 start 'bun server/server.ts' --name testserver"
  npm pkg set scripts.test:server:down="pm2 delete testserver"
  npm pkg set scripts.test:prisma:migrate="npx prisma migrate dev --name initial-setup --force"
  npm pkg set scripts.test:docker:up="docker compose -f docker-compose.test.yml up -d"
  npm pkg set scripts.test:docker:down="docker compose -f docker-compose.test.yml down"
  npm pkg set scripts.test:run="vitest run"
  npm pkg set scripts.test-all="npm run test:docker:up && npx dotenv-cli -e .env.test -- npm run test:prisma:migrate && npx dotenv-cli -e .env.test -- npm run test:server:up && npx dotenv-cli -e .env.test -- npm run test:run; npm run test:server:down && npm run test:docker:down"

  fi

else
  echo "Vitest setup skipped."
fi


# Open the project in VSCode
code .

# Run the frontend code in PM2
if $ADD_EXPRESS; then
  cd frontend
    pm2 start 'npm run dev' --name devclient
  cd ..
else
  pm2 start 'npm run dev' --name devclient
fi



# Wait half a second and then fire up the browser
sleep .5
open http://localhost:5173/


# Fire up PM2 logs if we have a server running there
# This will give us the server console messages.
if $ADD_EXPRESS; then
pm2 logs
fi








# TO DO
#
#
# Add a better .env default and .env.example
#
# Make README.md boilerplate better
#
# Fix the test suite part of this script so it works again with new folder structure.
#
# Give the app a script that lets you fire up all created elements using pm2 at a later stage, and then use that in this script.
#